# Generated by Django 2.2 on 2020-12-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='author',
            new_name='company',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill',
            field=models.ManyToManyField(to='users.Skill'),
        ),
    ]
