# Generated by Django 2.2.7 on 2021-04-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20201209_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'vacancies'},
        ),
    ]
